### ISSUE TITLE
Issue with seaweed

### ISSUE THREAD

**Issue by Balajanovski** [Balajanovski/Nautilus.io#1]
Due to `absolute` positioning, the seaweed on the home page doesn't stay put, and can lead to some strange results.

<img src="https://cdn.pbrd.co/images/6iNyicGWC.png" alt="seaweed pic">

**Comment by Balajanovski** [comment]
The seaweed moves up with the browser window instead of staying put on top of the seabed.
I believe a new approach to positioning must be employed instead of `absolute`

**Comment by Balajanovski** [comment]
Issue resolved.

**Comment by Balajanovski** [comment]
@ZaneHannanAU 
Zane, by removing `margin-top: -(some value)px` you have broken the seaweed bug again and made the seabed off screen.

**Comment by ZaneHannanAU** [comment]
Already fixed

On 6 December 2016 8:23:30 pm AEDT, James Balajan <notifications@github.com> wrote:
>@ZaneHannanAU 
>Zane, by removing `margin-top: -(some value)px` you have broken the
>seaweed bug again and made the seabed off screen.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Balajanovski/Nautilus.io/issues/1#issuecomment-265100902

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Balajanovski** [comment]
@ZaneHannanAU 
Explain this:
[![Screen Shot 2016-12-07 at 6.41.35 AM.png](https://s12.postimg.org/h0v5nhrl9/Screen_Shot_2016_12_07_at_6_41_35_AM.png)](https://postimg.org/image/aaeoe24fd/)

**Comment by ZaneHannanAU** [comment]
All I see is a white screen. Can you drop it into the form field?

On 7 December 2016 6:43:33 am AEDT, James Balajan <notifications@github.com> wrote:
>@ZaneHannanAU 
>Explain this:
>[![Screen Shot 2016-12-07 at 6.41.35
>AM.png](https://s12.postimg.org/h0v5nhrl9/Screen_Shot_2016_12_07_at_6_41_35_AM.png)](https://postimg.org/image/aaeoe24fd/)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Balajanovski/Nautilus.io/issues/1#issuecomment-265251916

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ZaneHannanAU** [comment]
Now I can see it.

The issue is the `bottom` attribute.

**Comment by ZaneHannanAU** [comment]
What it looks like with a full page screen capture

![screencapture-balajanovski-github-io-nautilus-io-1481058112454](https://cloud.githubusercontent.com/assets/20490671/20943464/9df7dea2-bc53-11e6-8674-a17165798a6b.png)

![screencapture-balajanovski-github-io-nautilus-io-1481057918602](https://cloud.githubusercontent.com/assets/20490671/20943469/9fccbfe0-bc53-11e6-933f-cf3a4b30d873.png)

**Comment by Balajanovski** [comment]
@ZaneHannanAU God damn it Zane, come to school I'll explain.

**Comment by Balajanovski** [comment]
@ZaneHannanAU This is what you have done

1. The seaweed scrolls with the y-axis leading to weird results.
2. I do not understand why you need y-axis scrolling

 

Excuse my frustration, but it just looks like you've royally screwed over my website.

Img 1: 
<img src="https://cdn.pbrd.co/images/6IEtWz1T9.png">

Img 2:
<img src="https://cdn.pbrd.co/images/6IFirWHCf.png">

**Comment by Balajanovski** [comment]
Issue resolved
@ZaneHannanAU Please do not spam commits, instead put all changes in one big commit, makes it seem a  lot cleaner instead of 100 commits with 1 line changes.

**Comment by Balajanovski** [comment]
Thanks Zane
